version: '3'

services:
  common: &BASE
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    depends_on:
      - mongo

  tests:
    <<: *BASE
    command: /app/gradlew test -i

  mongo:
    image: mongo:4.2.1
    command: "--smallfiles"

  dev:
    <<: *BASE
    volumes:
      - .:/app
    command: /app/gradlew bootRun
